name: CI/CD

on:
  push:
  pull_request:

env:
  AWS_REGION: "eu-west-1"

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: clone into repo
        uses: actions/checkout@v2

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

      - name: test index.html
        run: test -f public/index.html
        
      - name: test controller.js
        run: test -f public/js/controller.js

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    env:
      AWS_S3_BUCKET_NAME : "test.today.noi.bz.it"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./public

  deploy-prod:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/prod'
    needs: test
    concurrency: deploy-prod
    env:
      AWS_S3_BUCKET_NAME : "today.noi.bz.it"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Configure Google Analytics
        run: sed -i -e "s%GOOGLE_ANALYTICS_ID%${{ secrets.GOOGLE_ANALYTICS_ID_PROD }}%g" public/index.html

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./public